version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_DATABASE: turismo
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: "no"  # Agregar esta línea para deshabilitar el reinicio automático
      
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=turismo
      - DB_USER=root
      - DB_PASS=administrador
   
    
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

