version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_DATABASE: turismo
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: "no"  # Agregar esta línea para deshabilitar el reinicio automático
      
  web:
    image: httpd:latest
    container_name: web
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/

  django:
    build: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql