version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_DATABASE: turismo
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: "no"  # Agregar esta línea para deshabilitar el reinicio automático
      
