# Generated by Django 5.0.6 on 2024-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dni', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('fechaNacimiento', models.DateField(auto_now=True)),
                ('usuario', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=60)),
                ('foto', models.CharField(max_length=250)),
                ('fotoMiniatura', models.CharField(max_length=250)),
            ],
        ),
    ]
