# Generated by Django 5.0.6 on 2024-07-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Suscripto',
        ),
    ]
