# Generated by Django 5.0.6 on 2024-07-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptos', '0002_rename_subscription_suscripto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripto',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
